apiVersion: v1
kind: Pod
metadata:
  name: docker-dind
spec:
  securityContext: 
  volumes:
  - hostPath:
      path: /var/run/docker.sock
      type: ""
    name: volume-0
  containers:
  - name: dind
    image: docker-registry.default.svc:5000/docker-dind-test/jnlp:0.0.142
    imagePullPolicy: IfNotPresent
    name: jnlp
    resources: {}
    securityContext:
      fsGroup: 1000000000
      seLinuxOptions:
        level: s0:c1,c0
        type: spc_t
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      privileged: false
      runAsUser: 1000130000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: volume-0
    command: ['sh','-c','echo teste123455 && sleep 3600']
    env:
    - name: HOME
      value: /home/jenkins
